name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Copiar el archivo .env.template a .env
      - name: Create .env from .env.template
        run: cp .env.template .env

      # Paso 3: Cargar las variables de entorno desde .env
      - name: Set up environment variables
        run: |
          export $(cat .env | xargs)

      # Paso 4: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 5: Compilar y subir la imagen de Docker a Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-backend-image:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 6: Notificar a Render para redeploy
      - name: Notify Render to redeploy service
        run: |
          curl -X POST https://api.render.com/deploy \
            -H 'Accept: application/json' \
            -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'