name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Autenticarse en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 4: Construir y subir la imagen de Docker a Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: kuajinaiss/backend-taller3:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Paso 5: Notificar a Render para redesplegar el servicio
      - name: Notify Render to redeploy service
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cttm6kjv2p9s738jo2og?key=cRXaQiuvfaA" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"